
import = [
    "~/.config/alacritty/alacritty.base.toml",
]

[font.bold]
family = "JetBrains Mono NL"
style = "Bold"

[font.italic]
family = "JetBrains Mono NL"
style = "Italic"

[font.normal]
family = "JetBrains Mono NL"
style = "Regular"

