
[general]
import = [
    "~/.config/alacritty/alacritty.base.toml",
]

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[window]
option_as_alt = "OnlyLeft"

