[bell]
duration = 50
color = "#1E1E2E"

[font]
size = 12.5

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[window]
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 120
lines = 60
